name: Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build:
    if: github.event.head_commit.message == 'kaniko' 

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
     
      - name: GitHub Package Registry
        uses: aevea/action-kaniko@master
        with:
          registry: docker.pkg.github.com
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
          build_file: ./Dockerfile
          image: kaniko1
          tag: ${{ steps.slug.outputs.sha8 }}
          cache: true
          cache_registry: cache



      - name: Show Images
        run : docker images

